language: csharp
mono: none
dist: xenial
dotnet: 3.1
install:
  - dotnet restore --source https://nuget.emzi0767.com/api/v3/index.json --source https://api.nuget.org/v3/index.json
script:
  - dotnet build