language: csharp
mono: none
dist: xenial
dotnet: 3.1
env:
  global:
    - CONFIGURATION: Release
    - RUNTIME: win-x64
install:
  - dotnet restore --source https://nuget.emzi0767.com/api/v3/index.json --source https://api.nuget.org/v3/index.json
script:
  - dotnet publish -c "$CONFIGURATION" -r "$RUNTIME" -o "./publish/$CONFIGURATION/$RUNTIME" --no-self-contained
before_deploy:
  - cd "./publish/$CONFIGURATION/$RUNTIME"
  - TIMESTAMP=$(date '+%Y%m%d%H%M%S')
  - zip -r "TK.RaidBot-$RUNTIME-$TIMESTAMP.zip" .
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: PZx1puMvzg+MOU2UEs/NW9s7oeVDWRKuU+1VdSuWCc+1pb2Bl8XalLJ4uIdBr1HOD2Vs4rblduCFcJabk/VeuqFBLxOPlPn0ORc2SlqilhWjbIM5PLVnczTvfuQoi1J+Lw3XyXypqKeJaNYHCHqgbMEl+RYTJzJjYo1gb2zCTXu/QuRTgR1Z9/B3xrPklyArZoYlcVNuU6QDgQRP3Pb4GkNp0FmDEZ+h3Yo74m9sTqKPrOZ8Cr2P/jFTGHdsO6ygfPJI0iSzebMImVzuMqTInlfJ3AlMkdE+pub+8DLjhT4jbz2+wNrMAOxk+66VobFVoZsuc1bbfVdWA/vtXCL+UbdyOxcfuu7ImMyjmnliHjml1sOqBd5jfs6PLv/EJqhrRVdBdvFbf2HXpXsYGrc2D04Z2YiQAQo+SweXKYg26BFjt9ClL4aAkG0DcRCUW0uPgFtzyQ1bzWaMtmwh+32EBZdm0P6JgNEBg/ScALHsh4NggpBkqcT6wrq0vy/oZyuSiOxetDdniPu1YufEDvvGZZAYeT2z26+P+NlSQ7Mah4DBVfW37jVSs/ln1rMNKUOPAqg7n7sSVF0uFBdX0wOq3DlexzJbRA6ntsCIpyoLu/NRl8e51rRmfA8wNyJKXpR0Itl+mOxaIwVlGqG6b7UKQf2KpAhaZXrFLLP8+veQLK4=
  file: 
    - "TK.RaidBot-$RUNTIME-$TIMESTAMP.zip"
  on:
    branch: master