language: csharp
mono: none
dist: xenial
dotnet: 3.1
env:
  global:
    - CONFIGURATION: Release
    - RUNTIME: win-x64
install:
  - dotnet restore --source https://nuget.emzi0767.com/api/v3/index.json --source https://api.nuget.org/v3/index.json
script:
  - dotnet publish -c "$CONFIGURATION" -r "$RUNTIME" -o "./publish/$CONFIGURATION/$RUNTIME" --no-self-contained
before_deploy:
  - cd "./publish/$CONFIGURATION/$RUNTIME"
  - TIMESTAMP=$(date '+%Y%m%d%H%M%S')
  - zip -r "TK.RaidBot-$RUNTIME-$TIMESTAMP.zip" .
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: WB6QHkohWF97+LVgY1PVNoqnSiCBaK0CmbD/DGqMDgEPSjezvxOgIgZ8P7gWoka+W86vff1sFvHbxNbuzsTQVbBiYavwwWuyM6h6OhwbOqG9x7kvZzsfrYpi6VMVtFtKVNdTPEky1K6K2Oi93QG2p0Jvy7idSVSmZTIya/JeA2Ywewol+16nUtCKyg8Pv9UEFdAB+fUPXad+Nh26l9y9I00GeqlhYNWEgzc2LgGfe8Vj/3mSDOgnEIt8yYfHq+NSm0LFbo5pVhP9h8rQ6HDPfMYv+3VHtdfiJg9Z/rsh07SizpgQYn3Ie62qEmj5YLYPP/kkLAKKkTFJT5+zyz/HsZaje30H6b7l0GanIU1l83LO5eZwXoaEl2lwrUVC5hoFDsTI3UHrQ3eIrcycdAlMUZo8sJkdTO93Pf/ROWQ53YSxLXD7rSM6dJcxfK9osoE4kqYY0AmXwNG2rJOO9/yU1Swy9ijisD6sVbORLFto9WPPFo7O9OtcYPmlwF3KWsgWVcUqN/lVJjZPEEIH8WuauzL19iS3pAEb+VdZ/ax3L+ir+pTJQ6Rx5gvr8k3XVN4JoeVJvUESgPFBK+SMSpaBC6p7PP0lJaptIAFBs2EDYqGpMplXLsjjLLY+frM3fLy+8lc/yUqvQpfWWEPZfz8Gs2ph2LtAzuZ5Yroh33BqFQ0=
  file: 
    - "TK.RaidBot-$RUNTIME-$TIMESTAMP.zip"
  on:
    branch: master